<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>FableAstra</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>companion.ico</ApplicationIcon>
    <Version>1.2.1</Version>
    <Company>Desktop Companions</Company>
    <Description>Fable chan and Astra chan desktop companions</Description>
  </PropertyGroup>
</Project>
